registry_url: "{{ vault_registry_url }}"
image_nginx: "{{ vault_image_nginx }}"
image_app: "{{ vault_image_app }}"
image_front: "{{ vault_image_front }}"
registry_user: "{{ vault_registry_user }}"
registry_password: "{{ vault_registry_token }}"
app_ya_rasp_api_key: "{{ vault_ya_rasp_api_key }}"
app_database_url: "{{ vault_database_url }}"
app_sync_station_list: "{{ vault_app_sync_station_list }}"
app_dashboard_last_station_count: "15"
app_dashboard_last_station_list_sync_count: "5"
app_dashboard_last_station_list_download_count: "5"
amazon_s3_endpoint: "{{ vault_amazon_s3_enpoint }}"
amazon_s3_key: "{{ vault_amazon_s3_key }}"
amazon_s3_secret: "{{ vault_amazon_s3_secret }}"
amazon_s3_bucket: "{{ vault_amazon_s3_bucket }}"
amazon_s3_region: "{{ vault_amazon_s3_region }}"
amazon_s3_version: "{{ vault_amazon_s3_version }}"
app_storage_type: "{{ vault_app_storage_type }}"
messenger_transport_dsn: "{{ vault_messenger_transport_dsn }}"
